New command: `/changelog`
LeRoiDesKiwis/Omega-Bot pull request #5
Opened 2024-06-16 00:39 UTC by apoleon33

# if a changelog has been found
![image](https://github.com/LeRoiDesKiwis/Omega-Bot/assets/71031475/55d4b52c-e66a-4c93-874b-9a752ceec0f8)

# if not
![image](https://github.com/LeRoiDesKiwis/Omega-Bot/assets/71031475/34b72a95-94ee-4648-bcd3-ae1c031de693)

2024-06-16 11:24 UTC, LeRoiDesKiwis requested changes

2024-06-16 11:24 UTC, LeRoiDesKiwis commented on src/main/java/fr/leroideskiwis/omegabot/command/other/ChangelogCommand.java
> +            builder.addField("Pas de changelog pour la v" + Main.version + " trouvé:", e.getMessage(), false);
Pas besoin du e.getMessage(), tu peux juste lettre "Pas de changelog pour la v[version]"

2024-06-16 11:24 UTC, LeRoiDesKiwis commented on src/main/java/fr/leroideskiwis/omegabot/command/other/ChangelogCommand.java
> +            Scanner fileReader = new Scanner(new File(changelogFilePath));
Utilise plutôt Files.readAllLines()

2024-06-16 13:39 UTC, LeRoiDesKiwis requested changes

2024-06-16 13:39 UTC, LeRoiDesKiwis commented on src/main/java/fr/leroideskiwis/omegabot/command/other/ChangelogCommand.java
> +            builder.addField("Pas de changelog pour la v" + Main.version + " trouvé:", "", false);
Utilise setDescription plutôt qu'un field vide + y'a un ":" en trop

2024-06-16 16:29 UTC, LeRoiDesKiwis commented
Btw il manque :
- [ ] le fait qu'on puisse ajouter un argument (par exemple /version 1.3.0)
- [ ] si on fait /changelog list ça donne la liste des versions
![image](https://github.com/LeRoiDesKiwis/Omega-Bot/assets/35999932/5d415cb0-1280-4ca4-984b-9788f95f9c8a)

2024-06-16 17:39 UTC, LeRoiDesKiwis requested changes

2024-06-16 17:39 UTC, LeRoiDesKiwis commented on src/main/java/fr/leroideskiwis/omegabot/command/other/ChangelogCommand.java
> +            errorBuilder.addField(changelogNumber + " n'est pas un numéro de version valide", "Le numéro de version doit être de la forme X.Y.Z (ex: " + Main.version + ")", false);
Met plutôt "changelogNumber + " n'est pas un numéro de version valide" dans le titre et "Le numéro de version doit être de la forme X.Y.Z (ex: " + Main.version + ")" en description

2024-06-16 18:12 UTC, LeRoiDesKiwis commented
A faire :
j'ai un fichier
```
feat: add bombs (#6)
feat: display how many points are needed to purchase something
feat: add classement command
fix(givepoints): now show target's solde instead of sender
truc qui commence pas par feat ou fix
```
je dois avoir à la fin :

# Features
- add bombs (#6)
- display how many points are needed to purchase something
- add classement command
# Fixes
- givepoints: now show target's solde instead of sender
# Other
- truc qui commence pas par feat ou fix


Au mieux il faut faire en sorte qu'on puisse facilement rajouter des préfixes, par exemple si je veux rajouter un préfixe "test:" je dois pouvoir le faire facilement

2024-06-17 16:25 UTC, LeRoiDesKiwis requested changes
Bien mais maintenant va falloir gérer les feat(scope) etc mdrr

2024-06-18 13:53 UTC, apoleon33 commented
The UML btw:
![image](https://github.com/LeRoiDesKiwis/Omega-Bot/assets/71031475/ef610ca9-7bdf-4a92-bf21-06a445d98833)

2024-06-18 14:28 UTC, LeRoiDesKiwis approved these changes

2024-06-18 14:32 UTC, merged